### ISSUE TITLE
List type error in video dim

### ISSUE THREAD

**Issue by adeebakausar** [GV1028/videogan#5]
absl.flags._exceptions.IllegalFlagValueError: flag --video_dim=[32, 64, 64, 3]: Expect argument to be a string or int, found <type 'list'>

**Comment by ghost** [comment]
hi 
 while running your code i am getting this error. kindly help me to resolve the issue. I have used videos in gif format of 64x64 dimension RGB and 32 frames. and folder contain the videos of same action class. kindly help me to resolve the issue

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flag.py", line 181, in _parse
    return self.parser.parse(argument)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_argument_parser.py", line 152, in parse
    val = self.convert(argument)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_argument_parser.py", line 268, in convert
    type(argument)))
TypeError: Expect argument to be a string or int, found <class 'list'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    flags.DEFINE_integer("video_dim", [32,64,64,3], "The dimension of each video, must be of shape [frames, height, width, channels]")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_defines.py", line 315, in DEFINE_integer
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flag.py", line 110, in __init__
    self._set_default(default)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flag.py", line 211, in _set_default
    self.default = self._parse(value)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flag.py", line 184, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --video_dim=[32, 64, 64, 3]: Expect argument to be a string or int, found <class 'list'>

**Comment by ghost** [comment]
Now i have passed video_dim and lambd as the argument still i am getting this error

  File "main.py", line 35
    videogan = VideoGAN(sess,video_dim,zdim = FLAGS.zdim,batch_size = FLAGS.batch_size,epochs=FLAGS.epoch,checkpoint_file = FLAGS.checkpoint_file,lambd)
                                                                                                                                                 ^
SyntaxError: positional argument follows keyword argument

**Comment by hmlee10kr** [comment]
Hi! I am getting the same error, would anybody show me how it was solved? I'm completely stuck.
